[package]
name = "hello-world"
version = "0.1.0"
authors = ["Dmitry Kalmykov"]
edition = "2018"
features = ["os-poll", "tcp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
mio = "0.6"